//Autogenerated from Permissions.tt

using System.ComponentModel.DataAnnotations;

namespace Domain.Permissions
{
    public static class Permissions
    {
        #region Admin
        public static class User
        {
            [Display(Name = "CreateUserPermission")]
            public const string Create = "User_Create";
            [Display(Name = "UpdateUserPermission")]
            public const string Update = "User_Update";
            [Display(Name = "ReadUserPermission")]
            public const string Read = "User_Read";
            [Display(Name = "DeleteUserPermission")]
            public const string Delete = "User_Delete";
        }
        public static class TopicPermission
        {
            [Display(Name = "CreateTopicPermission")]
            public const string Create = "Topic_Create";
            [Display(Name = "UpdateTopicPermission")]
            public const string Update = "Topic_Update";
            [Display(Name = "ReadTopicPermission")]
            public const string Read = "Topic_Read";
            [Display(Name = "DeleteTopicPermission")]
            public const string Delete = "Topic_Delete";
        }
        public static class Role
        {
            [Display(Name = "CreateRolePermission")]
            public const string Create = "Role_Create";
            [Display(Name = "UpdateRolePermission")]
            public const string Update = "Role_Update";
            [Display(Name = "ReadRolePermission")]
            public const string Read = "Role_Read";
            [Display(Name = "DeleteRolePermission")]
            public const string Delete = "Role_Delete";
        }

        public static class Language
        {
            [Display(Name = "CreateLanguagePermission")]
            public const string Create = "Language_Create";
            [Display(Name = "UpdateLanguagePermission")]
            public const string Update = "Language_Update";
            [Display(Name = "ReadLanguagePermission")]
            public const string Read = "Language_Read";
            [Display(Name = "DeleteLanguagePermission")]
            public const string Delete = "Language_Delete";
        }

        public static class TopicOfInterest
        {
            [Display(Name = "AddSubTopicPermission")]
            public const string AddSubTopic = "AddSubTopic";
            [Display(Name = "AddTopicOfInterestPermission")]
            public const string AddTopicOfInterest = "AddTopicOfInterest";
            [Display(Name = "GetSubTopicsPermission")]
            public const string GetSubTopics = "GetSubTopics";
            [Display(Name = "ReadTopicRelatedPermission")]
            public const string ReadTopicRelated = "ReadTopicRelated";
            [Display(Name = "UserExcludedTopicsPermission")]
            public const string UserExcludedTopics = "UserExcludedTopics";
            [Display(Name = "ExcludedTopicsPermission")]
            public const string ExcludedTopics = "ExcludedTopics";
        }

        #endregion
    }
}