version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80:80"  # Expose Seq UI
      - "5341:5341"  # Expose Seq ingestion port
    volumes:
      - seq-data:/data  # Mount a volume for Seq data storage

volumes:
  seq-data:
