version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "80:80"  # Expose Seq UI
      - "5341:5341"  # Expose Seq ingestion port
    volumes:
      - seq-data:/data  # Mount a volume for Seq data storage
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   ports:
  #     - "9200:9200"  # Expose Elasticsearch HTTP port
  #     - "9300:9300"  # Expose Elasticsearch transport port
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data  # Mount a volume for Elasticsearch data storage

volumes:
  seq-data:
  # es-data:
